<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<DebugType>embedded</DebugType>
		<VersionPrefix>1.0.3</VersionPrefix>
		<VersionSuffix>dev</VersionSuffix>
		<RootNamespace>MiraModule</RootNamespace>
		<Description>Mira Module addon for Town of Us Mira</Description>
		<Authors>Ninja AU Modding, Goober, Ninja</Authors>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\**\*.*" />
		<EmbeddedResource Include="HarvesterAbilities\Resources\**\*.*" />
		<EmbeddedResource Include="modinfo.json" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Buttons\Crewmates\" />
	  <Folder Include="Options\Roles\Crewmates\" />
	</ItemGroup>
	
	<PropertyGroup>
		<NoWarn>CS1591;CA1707</NoWarn>
	</PropertyGroup>

	<Import Project="../AmongUs.props" />

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy /Y &quot;$(TargetPath)&quot; &quot;D:\Steam\steamapps\common\Among Us - TOU - Submerged - DEV\BepInEx\plugins\&quot;" ContinueOnError="true" />
	</Target>
</Project>
