<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<DebugType>embedded</DebugType>
		<VersionPrefix>1.0.3</VersionPrefix>
		<VersionSuffix>dev</VersionSuffix>
		<RootNamespace>MiraModule</RootNamespace>
		<Description>MiraModule addon for Town of Us Mira</Description>
		<!-- <Authors>your name</Authors> -->
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\**\*.*" />
	</ItemGroup>

	<Import Project="../AmongUs.props" />
</Project>