<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<DebugType>embedded</DebugType>
		<VersionPrefix>1.0.3</VersionPrefix>
		<VersionSuffix>dev</VersionSuffix>
		<RootNamespace>MiraOverloaded</RootNamespace>
		<Description>Mira Overloaded addon for Town of Us Mira</Description>
		<Authors>Goober, Asterisk, The Glitch, washed bac, Atony</Authors>
		<EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\**\*.*" />
		<EmbeddedResource Include="modinfo.json" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Buttons\Crewmate\" />
	  <Folder Include="Modifiers\Crewmate\" />
	  <Folder Include="Rules\" />
	</ItemGroup>
	
	<PropertyGroup>
		<NoWarn>CS1591;CA1707</NoWarn>
		<LocalPluginsPath>D:\Steam\steamapps\common\Among Us - TOU - MiraOverloaded\BepInEx\plugins\</LocalPluginsPath>
	</PropertyGroup>

	<Import Project="../AmongUs.props" />

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="Exists('$(LocalPluginsPath)')">
		<Exec Command="copy /Y &quot;$(TargetPath)&quot; &quot;$(LocalPluginsPath)&quot;" />
	</Target>
</Project>
